# Generated by Django 3.1.1 on 2021-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sroll', models.IntegerField()),
                ('sname', models.CharField(max_length=200)),
                ('sfname', models.CharField(max_length=200)),
                ('sage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('tage', models.IntegerField()),
                ('tsubject', models.CharField(max_length=200)),
            ],
        ),
    ]
